lakes:
  transient: 'gs://dna_commons/transient'
  raw: 'gs://dna_commons/raw'
  trusted: 'gs://dna_commons/trusted'
  refined: 'gs://dna_commons/refined'
  models: 'gs://dna_commons/models'
  backup: 'gs://dna_commons/backup'
  secrets: 'gs://dna_commons/secrets'
  config: 'gs://dna_commons/config'
