lakes:
  transient: 'gs://{BUCKET}/transient'
  raw: 'gs://{BUCKET}/raw'
  trusted: 'gs://{BUCKET}/trusted'
  refined: 'gs://{BUCKET}/refined'
  models: 'gs://{BUCKET}/models'
  backup: 'gs://{BUCKET}/backup'
  secrets: 'gs://{BUCKET}/secrets'
  config: 'gs://{BUCKET}/config'
